spring:
  data:
    mongodb:
      uri: ${MONGO_URL}
      database: ${MONGO_DATABASE}
      
#       database: cricApp
#       port: 27017
#       host: localhost
  application:
    name: recommendationservice
server:
  port: 9200
eureka:
  client:
   register-with-eureka: true
   fetch-registry: true
   service-url:
      default-zone: http://localhost:8761/eureka