spring:
 datasource:
  url: ${MYSQL_URL}
  username: ${MYSQL_USER}
  password: ${MYSQL_PASSWORD} 
 
   #url: jdbc:mysql://localhost:3306/cricapp
   #username: root
   #password: admin
 jpa:
   hibernate:
    ddl-auto: create
   show-sql: true
   database-platform: org.hibernate.dialect.MariaDBDialect
 application:
   name: user-auth
server:
 port: 9100
eureka:
 client:
   register-with-eureka: true
   fetch-registry: true
   service-url:
     default-zone: http://localhost:8761/eureka      